Added methods for Creating role and Ask for token
ConcoMB/bento pull request #2
Opened 2023-01-03 13:30 UTC by pablouboldi

2023-01-09 20:03 UTC, ConcoMB requested changes

2023-01-09 20:03 UTC, ConcoMB commented on arena_tokens.txt
> +1056963599584727121: sdfsdfsdf
esto deberia estar en el .gitignore o no?

Aparte, deberiamos ver como encriptarlo

2023-01-09 20:03 UTC, ConcoMB commented on main.py
> +        Step 2) defining the inputs
Pongamos un comment para no olvidarnos la parte esa de verificar si un token es valido o no

2023-01-13 17:39 UTC, pablouboldi commented
Creo que el archivo arena_tokens.txt deberia estar fuera de .gitignore porque los tokens ya estan encriptados

2023-01-13 18:32 UTC, ConcoMB requested changes

2023-01-13 18:32 UTC, ConcoMB commented on main.py
> +        with open('arena_tokens.txt', 'r') as f:
Pone el path al archivo como una constante a nivel raiz del archivo

2023-01-13 18:32 UTC, ConcoMB commented on main.py
> +        user_handle = f'{member.name}%23{member.discriminator}'
Pq lo armas a mano? no encontraste alguna funcion que lo pase a http safe?

2023-01-13 18:32 UTC, ConcoMB commented on main.py
> +        url_endpoint = f"{dashboard_endpoint}/discord_connections?"
los paths a los endpoints manejalos como constante tb. y capaz todo esto de aca podria estar en una funcion que sea build_url o algo asi

2023-01-13 18:32 UTC, ConcoMB commented on arena_tokens.txt
> +1058058737094508625: pMgan0/aBA39ga1+SNd+9g==
El archivo deberia estar gitignorado. No importa q este encriptado. No es parte del codebase, es dato del negocio. Pensalo como si fuesa una base de datos. No va aca, Se usa aca pero no es parte de algo que queres versionar y/o compartir entre devs

2023-01-16 14:45 UTC, pablouboldi commented on main.py
> +        user_handle = f'{member.name}%23{member.discriminator}'
Si, uso el metodo urllib.parse.quote(), pero como el user handle es siempre igual, me parecio mas rapido hacerlo a mano, pero ya lo hice con el metodo.

2023-01-16 14:55 UTC, pablouboldi commented on main.py
> +        url_endpoint = f"{dashboard_endpoint}/discord_connections?"
Ya cree la funcion para armar la url, pero no entendí lo de los path de los endpoints: dashboard_endpoint es una constante que la obtiene del .env

2023-01-16 18:15 UTC, ConcoMB approved these changes

2023-01-16 18:22 UTC, merged