Bento
ConcoMB/bento pull request #3
Opened 2023-01-20 17:53 UTC by pablouboldi

Las preguntas del modal las personaliza el dueño del server. Por ahora son todas obligatorias, no logré hacer que el dueño del server pueda definir su obligatoriedad (todavia)
El modal es para todos los usuarios del server, no solo para los verificados
Por ahora todas las respuestas de los usuarios van al mismo GSheet

2023-01-20 19:52 UTC, ConcoMB requested changes

2023-01-20 19:52 UTC, ConcoMB commented on modals.py
> +        # self.spreadsheet_id = '1fxV8yGONBjmykh8oLRGbt_D4_XGCwfpz7sU9O82tJmg'
Que es todo esto comentado?

2023-01-20 19:52 UTC, ConcoMB commented on modals.py
> +            "client_sheet_id": "1fxV8yGONBjmykh8oLRGbt_D4_XGCwfpz7sU9O82tJmg",
que es este id cableado? no debiese ser una env var?

2023-01-23 14:51 UTC, pablouboldi commented on modals.py
> +        # self.spreadsheet_id = '1fxV8yGONBjmykh8oLRGbt_D4_XGCwfpz7sU9O82tJmg'
Eran las preguntas del modal predefinidas por nosotros. Ya las borre porque el bot le pregunta al server owner que preguntas quiere hacer

2023-01-23 14:53 UTC, pablouboldi commented on modals.py
> +            "client_sheet_id": "1fxV8yGONBjmykh8oLRGbt_D4_XGCwfpz7sU9O82tJmg",
Ese id es el id de la google sheet a donde se van a cargar las respuestas del modal que responda el usuario del server. Por ahora cablee uno para ir probando, pero tengo que encontrar la manera de pedirle al server owner, de manera user friendly, a qué google sheet las quiere cargar porque no puedo pedirle el id, es medio engorroso.

2023-01-24 18:15 UTC, merged